// Code generated by ent, DO NOT EDIT.

package tooldependency

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the tooldependency type in the database.
	Label = "tool_dependency"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldType holds the string denoting the type field in the database.
	FieldType = "type"
	// FieldDependencyName holds the string denoting the dependency_name field in the database.
	FieldDependencyName = "dependency_name"
	// FieldDependencyVersion holds the string denoting the dependency_version field in the database.
	FieldDependencyVersion = "dependency_version"
	// FieldVersionRange holds the string denoting the version_range field in the database.
	FieldVersionRange = "version_range"
	// FieldIsRequired holds the string denoting the is_required field in the database.
	FieldIsRequired = "is_required"
	// FieldCondition holds the string denoting the condition field in the database.
	FieldCondition = "condition"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeTool holds the string denoting the tool edge name in mutations.
	EdgeTool = "tool"
	// Table holds the table name of the tooldependency in the database.
	Table = "tool_dependencies"
	// ToolTable is the table that holds the tool relation/edge.
	ToolTable = "tool_dependencies"
	// ToolInverseTable is the table name for the Tool entity.
	// It exists in this package in order to avoid circular dependency with the "tool" package.
	ToolInverseTable = "tools"
	// ToolColumn is the table column denoting the tool relation/edge.
	ToolColumn = "tool_dependencies"
)

// Columns holds all SQL columns for tooldependency fields.
var Columns = []string{
	FieldID,
	FieldType,
	FieldDependencyName,
	FieldDependencyVersion,
	FieldVersionRange,
	FieldIsRequired,
	FieldCondition,
	FieldCreatedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "tool_dependencies"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"tool_dependencies",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultIsRequired holds the default value on creation for the "is_required" field.
	DefaultIsRequired bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// Type defines the type for the "type" enum field.
type Type string

// TypeRUNTIME is the default value of the Type enum.
const DefaultType = TypeRUNTIME

// Type values.
const (
	TypeRUNTIME  Type = "RUNTIME"
	TypeBUILD    Type = "BUILD"
	TypeOPTIONAL Type = "OPTIONAL"
	TypePEER     Type = "PEER"
)

func (_type Type) String() string {
	return string(_type)
}

// TypeValidator is a validator for the "type" field enum values. It is called by the builders before save.
func TypeValidator(_type Type) error {
	switch _type {
	case TypeRUNTIME, TypeBUILD, TypeOPTIONAL, TypePEER:
		return nil
	default:
		return fmt.Errorf("tooldependency: invalid enum value for type field: %q", _type)
	}
}

// OrderOption defines the ordering options for the ToolDependency queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByType orders the results by the type field.
func ByType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldType, opts...).ToFunc()
}

// ByDependencyName orders the results by the dependency_name field.
func ByDependencyName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDependencyName, opts...).ToFunc()
}

// ByDependencyVersion orders the results by the dependency_version field.
func ByDependencyVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDependencyVersion, opts...).ToFunc()
}

// ByVersionRange orders the results by the version_range field.
func ByVersionRange(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVersionRange, opts...).ToFunc()
}

// ByIsRequired orders the results by the is_required field.
func ByIsRequired(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsRequired, opts...).ToFunc()
}

// ByCondition orders the results by the condition field.
func ByCondition(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCondition, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByToolField orders the results by tool field.
func ByToolField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newToolStep(), sql.OrderByField(field, opts...))
	}
}
func newToolStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ToolInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ToolTable, ToolColumn),
	)
}
