apiVersion: agentforge.dev/v1
kind: Prompt
metadata:
  name: complete-test-prompt
  namespace: default
  version: 1.0.0
  description: AI prompt for Complete Test Prompt
  author: AgentForge User <user@example.com>
  license: MIT
  homepage: ""
  documentation: ""
  tags: []
  categories: []
  keywords: []
  created: 2025-07-22T20:05:43+02:00

spec:
  prompt:
    type: TEMPLATE
    language: en
    template_file: template.txt
    variables_file: variables.json
    context_window: 4096
    supports_streaming: false
    
  variables:
    - name: task
      type: string
      description: "The task to help with"
      required: true
    - name: context
      type: string
      description: "Additional context for the task"
      required: false
      default: "No additional context provided"
    
  model_preferences:
    - gpt-4
    - claude-3-sonnet
    - gemini-pro
    
  configuration:
    temperature: 0.7
    max_tokens: 2048
    stop_sequences: []

stability: experimental
maturity: alpha
forge_version: "0.1.0"
platforms:
  - linux
  - darwin
  - windows
