// Code generated by ent, DO NOT EDIT.

package promptdependency

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/denkhaus/agentforge/internal/database/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.PromptDependency {
	return predicate.PromptDependency(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.PromptDependency {
	return predicate.PromptDependency(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.PromptDependency {
	return predicate.PromptDependency(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.PromptDependency {
	return predicate.PromptDependency(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.PromptDependency {
	return predicate.PromptDependency(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.PromptDependency {
	return predicate.PromptDependency(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.PromptDependency {
	return predicate.PromptDependency(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.PromptDependency {
	return predicate.PromptDependency(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.PromptDependency {
	return predicate.PromptDependency(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.PromptDependency {
	return predicate.PromptDependency(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.PromptDependency {
	return predicate.PromptDependency(sql.FieldContainsFold(FieldID, id))
}

// DependencyName applies equality check predicate on the "dependency_name" field. It's identical to DependencyNameEQ.
func DependencyName(v string) predicate.PromptDependency {
	return predicate.PromptDependency(sql.FieldEQ(FieldDependencyName, v))
}

// DependencyVersion applies equality check predicate on the "dependency_version" field. It's identical to DependencyVersionEQ.
func DependencyVersion(v string) predicate.PromptDependency {
	return predicate.PromptDependency(sql.FieldEQ(FieldDependencyVersion, v))
}

// VersionRange applies equality check predicate on the "version_range" field. It's identical to VersionRangeEQ.
func VersionRange(v string) predicate.PromptDependency {
	return predicate.PromptDependency(sql.FieldEQ(FieldVersionRange, v))
}

// IsRequired applies equality check predicate on the "is_required" field. It's identical to IsRequiredEQ.
func IsRequired(v bool) predicate.PromptDependency {
	return predicate.PromptDependency(sql.FieldEQ(FieldIsRequired, v))
}

// Condition applies equality check predicate on the "condition" field. It's identical to ConditionEQ.
func Condition(v string) predicate.PromptDependency {
	return predicate.PromptDependency(sql.FieldEQ(FieldCondition, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.PromptDependency {
	return predicate.PromptDependency(sql.FieldEQ(FieldCreatedAt, v))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v Type) predicate.PromptDependency {
	return predicate.PromptDependency(sql.FieldEQ(FieldType, v))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v Type) predicate.PromptDependency {
	return predicate.PromptDependency(sql.FieldNEQ(FieldType, v))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...Type) predicate.PromptDependency {
	return predicate.PromptDependency(sql.FieldIn(FieldType, vs...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...Type) predicate.PromptDependency {
	return predicate.PromptDependency(sql.FieldNotIn(FieldType, vs...))
}

// DependencyNameEQ applies the EQ predicate on the "dependency_name" field.
func DependencyNameEQ(v string) predicate.PromptDependency {
	return predicate.PromptDependency(sql.FieldEQ(FieldDependencyName, v))
}

// DependencyNameNEQ applies the NEQ predicate on the "dependency_name" field.
func DependencyNameNEQ(v string) predicate.PromptDependency {
	return predicate.PromptDependency(sql.FieldNEQ(FieldDependencyName, v))
}

// DependencyNameIn applies the In predicate on the "dependency_name" field.
func DependencyNameIn(vs ...string) predicate.PromptDependency {
	return predicate.PromptDependency(sql.FieldIn(FieldDependencyName, vs...))
}

// DependencyNameNotIn applies the NotIn predicate on the "dependency_name" field.
func DependencyNameNotIn(vs ...string) predicate.PromptDependency {
	return predicate.PromptDependency(sql.FieldNotIn(FieldDependencyName, vs...))
}

// DependencyNameGT applies the GT predicate on the "dependency_name" field.
func DependencyNameGT(v string) predicate.PromptDependency {
	return predicate.PromptDependency(sql.FieldGT(FieldDependencyName, v))
}

// DependencyNameGTE applies the GTE predicate on the "dependency_name" field.
func DependencyNameGTE(v string) predicate.PromptDependency {
	return predicate.PromptDependency(sql.FieldGTE(FieldDependencyName, v))
}

// DependencyNameLT applies the LT predicate on the "dependency_name" field.
func DependencyNameLT(v string) predicate.PromptDependency {
	return predicate.PromptDependency(sql.FieldLT(FieldDependencyName, v))
}

// DependencyNameLTE applies the LTE predicate on the "dependency_name" field.
func DependencyNameLTE(v string) predicate.PromptDependency {
	return predicate.PromptDependency(sql.FieldLTE(FieldDependencyName, v))
}

// DependencyNameContains applies the Contains predicate on the "dependency_name" field.
func DependencyNameContains(v string) predicate.PromptDependency {
	return predicate.PromptDependency(sql.FieldContains(FieldDependencyName, v))
}

// DependencyNameHasPrefix applies the HasPrefix predicate on the "dependency_name" field.
func DependencyNameHasPrefix(v string) predicate.PromptDependency {
	return predicate.PromptDependency(sql.FieldHasPrefix(FieldDependencyName, v))
}

// DependencyNameHasSuffix applies the HasSuffix predicate on the "dependency_name" field.
func DependencyNameHasSuffix(v string) predicate.PromptDependency {
	return predicate.PromptDependency(sql.FieldHasSuffix(FieldDependencyName, v))
}

// DependencyNameEqualFold applies the EqualFold predicate on the "dependency_name" field.
func DependencyNameEqualFold(v string) predicate.PromptDependency {
	return predicate.PromptDependency(sql.FieldEqualFold(FieldDependencyName, v))
}

// DependencyNameContainsFold applies the ContainsFold predicate on the "dependency_name" field.
func DependencyNameContainsFold(v string) predicate.PromptDependency {
	return predicate.PromptDependency(sql.FieldContainsFold(FieldDependencyName, v))
}

// DependencyVersionEQ applies the EQ predicate on the "dependency_version" field.
func DependencyVersionEQ(v string) predicate.PromptDependency {
	return predicate.PromptDependency(sql.FieldEQ(FieldDependencyVersion, v))
}

// DependencyVersionNEQ applies the NEQ predicate on the "dependency_version" field.
func DependencyVersionNEQ(v string) predicate.PromptDependency {
	return predicate.PromptDependency(sql.FieldNEQ(FieldDependencyVersion, v))
}

// DependencyVersionIn applies the In predicate on the "dependency_version" field.
func DependencyVersionIn(vs ...string) predicate.PromptDependency {
	return predicate.PromptDependency(sql.FieldIn(FieldDependencyVersion, vs...))
}

// DependencyVersionNotIn applies the NotIn predicate on the "dependency_version" field.
func DependencyVersionNotIn(vs ...string) predicate.PromptDependency {
	return predicate.PromptDependency(sql.FieldNotIn(FieldDependencyVersion, vs...))
}

// DependencyVersionGT applies the GT predicate on the "dependency_version" field.
func DependencyVersionGT(v string) predicate.PromptDependency {
	return predicate.PromptDependency(sql.FieldGT(FieldDependencyVersion, v))
}

// DependencyVersionGTE applies the GTE predicate on the "dependency_version" field.
func DependencyVersionGTE(v string) predicate.PromptDependency {
	return predicate.PromptDependency(sql.FieldGTE(FieldDependencyVersion, v))
}

// DependencyVersionLT applies the LT predicate on the "dependency_version" field.
func DependencyVersionLT(v string) predicate.PromptDependency {
	return predicate.PromptDependency(sql.FieldLT(FieldDependencyVersion, v))
}

// DependencyVersionLTE applies the LTE predicate on the "dependency_version" field.
func DependencyVersionLTE(v string) predicate.PromptDependency {
	return predicate.PromptDependency(sql.FieldLTE(FieldDependencyVersion, v))
}

// DependencyVersionContains applies the Contains predicate on the "dependency_version" field.
func DependencyVersionContains(v string) predicate.PromptDependency {
	return predicate.PromptDependency(sql.FieldContains(FieldDependencyVersion, v))
}

// DependencyVersionHasPrefix applies the HasPrefix predicate on the "dependency_version" field.
func DependencyVersionHasPrefix(v string) predicate.PromptDependency {
	return predicate.PromptDependency(sql.FieldHasPrefix(FieldDependencyVersion, v))
}

// DependencyVersionHasSuffix applies the HasSuffix predicate on the "dependency_version" field.
func DependencyVersionHasSuffix(v string) predicate.PromptDependency {
	return predicate.PromptDependency(sql.FieldHasSuffix(FieldDependencyVersion, v))
}

// DependencyVersionEqualFold applies the EqualFold predicate on the "dependency_version" field.
func DependencyVersionEqualFold(v string) predicate.PromptDependency {
	return predicate.PromptDependency(sql.FieldEqualFold(FieldDependencyVersion, v))
}

// DependencyVersionContainsFold applies the ContainsFold predicate on the "dependency_version" field.
func DependencyVersionContainsFold(v string) predicate.PromptDependency {
	return predicate.PromptDependency(sql.FieldContainsFold(FieldDependencyVersion, v))
}

// VersionRangeEQ applies the EQ predicate on the "version_range" field.
func VersionRangeEQ(v string) predicate.PromptDependency {
	return predicate.PromptDependency(sql.FieldEQ(FieldVersionRange, v))
}

// VersionRangeNEQ applies the NEQ predicate on the "version_range" field.
func VersionRangeNEQ(v string) predicate.PromptDependency {
	return predicate.PromptDependency(sql.FieldNEQ(FieldVersionRange, v))
}

// VersionRangeIn applies the In predicate on the "version_range" field.
func VersionRangeIn(vs ...string) predicate.PromptDependency {
	return predicate.PromptDependency(sql.FieldIn(FieldVersionRange, vs...))
}

// VersionRangeNotIn applies the NotIn predicate on the "version_range" field.
func VersionRangeNotIn(vs ...string) predicate.PromptDependency {
	return predicate.PromptDependency(sql.FieldNotIn(FieldVersionRange, vs...))
}

// VersionRangeGT applies the GT predicate on the "version_range" field.
func VersionRangeGT(v string) predicate.PromptDependency {
	return predicate.PromptDependency(sql.FieldGT(FieldVersionRange, v))
}

// VersionRangeGTE applies the GTE predicate on the "version_range" field.
func VersionRangeGTE(v string) predicate.PromptDependency {
	return predicate.PromptDependency(sql.FieldGTE(FieldVersionRange, v))
}

// VersionRangeLT applies the LT predicate on the "version_range" field.
func VersionRangeLT(v string) predicate.PromptDependency {
	return predicate.PromptDependency(sql.FieldLT(FieldVersionRange, v))
}

// VersionRangeLTE applies the LTE predicate on the "version_range" field.
func VersionRangeLTE(v string) predicate.PromptDependency {
	return predicate.PromptDependency(sql.FieldLTE(FieldVersionRange, v))
}

// VersionRangeContains applies the Contains predicate on the "version_range" field.
func VersionRangeContains(v string) predicate.PromptDependency {
	return predicate.PromptDependency(sql.FieldContains(FieldVersionRange, v))
}

// VersionRangeHasPrefix applies the HasPrefix predicate on the "version_range" field.
func VersionRangeHasPrefix(v string) predicate.PromptDependency {
	return predicate.PromptDependency(sql.FieldHasPrefix(FieldVersionRange, v))
}

// VersionRangeHasSuffix applies the HasSuffix predicate on the "version_range" field.
func VersionRangeHasSuffix(v string) predicate.PromptDependency {
	return predicate.PromptDependency(sql.FieldHasSuffix(FieldVersionRange, v))
}

// VersionRangeEqualFold applies the EqualFold predicate on the "version_range" field.
func VersionRangeEqualFold(v string) predicate.PromptDependency {
	return predicate.PromptDependency(sql.FieldEqualFold(FieldVersionRange, v))
}

// VersionRangeContainsFold applies the ContainsFold predicate on the "version_range" field.
func VersionRangeContainsFold(v string) predicate.PromptDependency {
	return predicate.PromptDependency(sql.FieldContainsFold(FieldVersionRange, v))
}

// IsRequiredEQ applies the EQ predicate on the "is_required" field.
func IsRequiredEQ(v bool) predicate.PromptDependency {
	return predicate.PromptDependency(sql.FieldEQ(FieldIsRequired, v))
}

// IsRequiredNEQ applies the NEQ predicate on the "is_required" field.
func IsRequiredNEQ(v bool) predicate.PromptDependency {
	return predicate.PromptDependency(sql.FieldNEQ(FieldIsRequired, v))
}

// ConditionEQ applies the EQ predicate on the "condition" field.
func ConditionEQ(v string) predicate.PromptDependency {
	return predicate.PromptDependency(sql.FieldEQ(FieldCondition, v))
}

// ConditionNEQ applies the NEQ predicate on the "condition" field.
func ConditionNEQ(v string) predicate.PromptDependency {
	return predicate.PromptDependency(sql.FieldNEQ(FieldCondition, v))
}

// ConditionIn applies the In predicate on the "condition" field.
func ConditionIn(vs ...string) predicate.PromptDependency {
	return predicate.PromptDependency(sql.FieldIn(FieldCondition, vs...))
}

// ConditionNotIn applies the NotIn predicate on the "condition" field.
func ConditionNotIn(vs ...string) predicate.PromptDependency {
	return predicate.PromptDependency(sql.FieldNotIn(FieldCondition, vs...))
}

// ConditionGT applies the GT predicate on the "condition" field.
func ConditionGT(v string) predicate.PromptDependency {
	return predicate.PromptDependency(sql.FieldGT(FieldCondition, v))
}

// ConditionGTE applies the GTE predicate on the "condition" field.
func ConditionGTE(v string) predicate.PromptDependency {
	return predicate.PromptDependency(sql.FieldGTE(FieldCondition, v))
}

// ConditionLT applies the LT predicate on the "condition" field.
func ConditionLT(v string) predicate.PromptDependency {
	return predicate.PromptDependency(sql.FieldLT(FieldCondition, v))
}

// ConditionLTE applies the LTE predicate on the "condition" field.
func ConditionLTE(v string) predicate.PromptDependency {
	return predicate.PromptDependency(sql.FieldLTE(FieldCondition, v))
}

// ConditionContains applies the Contains predicate on the "condition" field.
func ConditionContains(v string) predicate.PromptDependency {
	return predicate.PromptDependency(sql.FieldContains(FieldCondition, v))
}

// ConditionHasPrefix applies the HasPrefix predicate on the "condition" field.
func ConditionHasPrefix(v string) predicate.PromptDependency {
	return predicate.PromptDependency(sql.FieldHasPrefix(FieldCondition, v))
}

// ConditionHasSuffix applies the HasSuffix predicate on the "condition" field.
func ConditionHasSuffix(v string) predicate.PromptDependency {
	return predicate.PromptDependency(sql.FieldHasSuffix(FieldCondition, v))
}

// ConditionIsNil applies the IsNil predicate on the "condition" field.
func ConditionIsNil() predicate.PromptDependency {
	return predicate.PromptDependency(sql.FieldIsNull(FieldCondition))
}

// ConditionNotNil applies the NotNil predicate on the "condition" field.
func ConditionNotNil() predicate.PromptDependency {
	return predicate.PromptDependency(sql.FieldNotNull(FieldCondition))
}

// ConditionEqualFold applies the EqualFold predicate on the "condition" field.
func ConditionEqualFold(v string) predicate.PromptDependency {
	return predicate.PromptDependency(sql.FieldEqualFold(FieldCondition, v))
}

// ConditionContainsFold applies the ContainsFold predicate on the "condition" field.
func ConditionContainsFold(v string) predicate.PromptDependency {
	return predicate.PromptDependency(sql.FieldContainsFold(FieldCondition, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.PromptDependency {
	return predicate.PromptDependency(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.PromptDependency {
	return predicate.PromptDependency(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.PromptDependency {
	return predicate.PromptDependency(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.PromptDependency {
	return predicate.PromptDependency(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.PromptDependency {
	return predicate.PromptDependency(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.PromptDependency {
	return predicate.PromptDependency(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.PromptDependency {
	return predicate.PromptDependency(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.PromptDependency {
	return predicate.PromptDependency(sql.FieldLTE(FieldCreatedAt, v))
}

// HasPrompt applies the HasEdge predicate on the "prompt" edge.
func HasPrompt() predicate.PromptDependency {
	return predicate.PromptDependency(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, PromptTable, PromptColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPromptWith applies the HasEdge predicate on the "prompt" edge with a given conditions (other predicates).
func HasPromptWith(preds ...predicate.Prompt) predicate.PromptDependency {
	return predicate.PromptDependency(func(s *sql.Selector) {
		step := newPromptStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PromptDependency) predicate.PromptDependency {
	return predicate.PromptDependency(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PromptDependency) predicate.PromptDependency {
	return predicate.PromptDependency(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PromptDependency) predicate.PromptDependency {
	return predicate.PromptDependency(sql.NotPredicates(p))
}
