// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/denkhaus/agentforge/internal/database/ent/agent"
	"github.com/denkhaus/agentforge/internal/database/ent/agentdependency"
)

// AgentDependencyCreate is the builder for creating a AgentDependency entity.
type AgentDependencyCreate struct {
	config
	mutation *AgentDependencyMutation
	hooks    []Hook
}

// SetType sets the "type" field.
func (adc *AgentDependencyCreate) SetType(a agentdependency.Type) *AgentDependencyCreate {
	adc.mutation.SetType(a)
	return adc
}

// SetNillableType sets the "type" field if the given value is not nil.
func (adc *AgentDependencyCreate) SetNillableType(a *agentdependency.Type) *AgentDependencyCreate {
	if a != nil {
		adc.SetType(*a)
	}
	return adc
}

// SetDependencyName sets the "dependency_name" field.
func (adc *AgentDependencyCreate) SetDependencyName(s string) *AgentDependencyCreate {
	adc.mutation.SetDependencyName(s)
	return adc
}

// SetDependencyVersion sets the "dependency_version" field.
func (adc *AgentDependencyCreate) SetDependencyVersion(s string) *AgentDependencyCreate {
	adc.mutation.SetDependencyVersion(s)
	return adc
}

// SetVersionRange sets the "version_range" field.
func (adc *AgentDependencyCreate) SetVersionRange(s string) *AgentDependencyCreate {
	adc.mutation.SetVersionRange(s)
	return adc
}

// SetIsRequired sets the "is_required" field.
func (adc *AgentDependencyCreate) SetIsRequired(b bool) *AgentDependencyCreate {
	adc.mutation.SetIsRequired(b)
	return adc
}

// SetNillableIsRequired sets the "is_required" field if the given value is not nil.
func (adc *AgentDependencyCreate) SetNillableIsRequired(b *bool) *AgentDependencyCreate {
	if b != nil {
		adc.SetIsRequired(*b)
	}
	return adc
}

// SetCondition sets the "condition" field.
func (adc *AgentDependencyCreate) SetCondition(s string) *AgentDependencyCreate {
	adc.mutation.SetCondition(s)
	return adc
}

// SetNillableCondition sets the "condition" field if the given value is not nil.
func (adc *AgentDependencyCreate) SetNillableCondition(s *string) *AgentDependencyCreate {
	if s != nil {
		adc.SetCondition(*s)
	}
	return adc
}

// SetCreatedAt sets the "created_at" field.
func (adc *AgentDependencyCreate) SetCreatedAt(t time.Time) *AgentDependencyCreate {
	adc.mutation.SetCreatedAt(t)
	return adc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (adc *AgentDependencyCreate) SetNillableCreatedAt(t *time.Time) *AgentDependencyCreate {
	if t != nil {
		adc.SetCreatedAt(*t)
	}
	return adc
}

// SetID sets the "id" field.
func (adc *AgentDependencyCreate) SetID(s string) *AgentDependencyCreate {
	adc.mutation.SetID(s)
	return adc
}

// SetAgentID sets the "agent" edge to the Agent entity by ID.
func (adc *AgentDependencyCreate) SetAgentID(id string) *AgentDependencyCreate {
	adc.mutation.SetAgentID(id)
	return adc
}

// SetAgent sets the "agent" edge to the Agent entity.
func (adc *AgentDependencyCreate) SetAgent(a *Agent) *AgentDependencyCreate {
	return adc.SetAgentID(a.ID)
}

// Mutation returns the AgentDependencyMutation object of the builder.
func (adc *AgentDependencyCreate) Mutation() *AgentDependencyMutation {
	return adc.mutation
}

// Save creates the AgentDependency in the database.
func (adc *AgentDependencyCreate) Save(ctx context.Context) (*AgentDependency, error) {
	adc.defaults()
	return withHooks(ctx, adc.sqlSave, adc.mutation, adc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (adc *AgentDependencyCreate) SaveX(ctx context.Context) *AgentDependency {
	v, err := adc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (adc *AgentDependencyCreate) Exec(ctx context.Context) error {
	_, err := adc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (adc *AgentDependencyCreate) ExecX(ctx context.Context) {
	if err := adc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (adc *AgentDependencyCreate) defaults() {
	if _, ok := adc.mutation.GetType(); !ok {
		v := agentdependency.DefaultType
		adc.mutation.SetType(v)
	}
	if _, ok := adc.mutation.IsRequired(); !ok {
		v := agentdependency.DefaultIsRequired
		adc.mutation.SetIsRequired(v)
	}
	if _, ok := adc.mutation.CreatedAt(); !ok {
		v := agentdependency.DefaultCreatedAt()
		adc.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (adc *AgentDependencyCreate) check() error {
	if _, ok := adc.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "AgentDependency.type"`)}
	}
	if v, ok := adc.mutation.GetType(); ok {
		if err := agentdependency.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "AgentDependency.type": %w`, err)}
		}
	}
	if _, ok := adc.mutation.DependencyName(); !ok {
		return &ValidationError{Name: "dependency_name", err: errors.New(`ent: missing required field "AgentDependency.dependency_name"`)}
	}
	if _, ok := adc.mutation.DependencyVersion(); !ok {
		return &ValidationError{Name: "dependency_version", err: errors.New(`ent: missing required field "AgentDependency.dependency_version"`)}
	}
	if _, ok := adc.mutation.VersionRange(); !ok {
		return &ValidationError{Name: "version_range", err: errors.New(`ent: missing required field "AgentDependency.version_range"`)}
	}
	if _, ok := adc.mutation.IsRequired(); !ok {
		return &ValidationError{Name: "is_required", err: errors.New(`ent: missing required field "AgentDependency.is_required"`)}
	}
	if _, ok := adc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AgentDependency.created_at"`)}
	}
	if len(adc.mutation.AgentIDs()) == 0 {
		return &ValidationError{Name: "agent", err: errors.New(`ent: missing required edge "AgentDependency.agent"`)}
	}
	return nil
}

func (adc *AgentDependencyCreate) sqlSave(ctx context.Context) (*AgentDependency, error) {
	if err := adc.check(); err != nil {
		return nil, err
	}
	_node, _spec := adc.createSpec()
	if err := sqlgraph.CreateNode(ctx, adc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected AgentDependency.ID type: %T", _spec.ID.Value)
		}
	}
	adc.mutation.id = &_node.ID
	adc.mutation.done = true
	return _node, nil
}

func (adc *AgentDependencyCreate) createSpec() (*AgentDependency, *sqlgraph.CreateSpec) {
	var (
		_node = &AgentDependency{config: adc.config}
		_spec = sqlgraph.NewCreateSpec(agentdependency.Table, sqlgraph.NewFieldSpec(agentdependency.FieldID, field.TypeString))
	)
	if id, ok := adc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := adc.mutation.GetType(); ok {
		_spec.SetField(agentdependency.FieldType, field.TypeEnum, value)
		_node.Type = value
	}
	if value, ok := adc.mutation.DependencyName(); ok {
		_spec.SetField(agentdependency.FieldDependencyName, field.TypeString, value)
		_node.DependencyName = value
	}
	if value, ok := adc.mutation.DependencyVersion(); ok {
		_spec.SetField(agentdependency.FieldDependencyVersion, field.TypeString, value)
		_node.DependencyVersion = value
	}
	if value, ok := adc.mutation.VersionRange(); ok {
		_spec.SetField(agentdependency.FieldVersionRange, field.TypeString, value)
		_node.VersionRange = value
	}
	if value, ok := adc.mutation.IsRequired(); ok {
		_spec.SetField(agentdependency.FieldIsRequired, field.TypeBool, value)
		_node.IsRequired = value
	}
	if value, ok := adc.mutation.Condition(); ok {
		_spec.SetField(agentdependency.FieldCondition, field.TypeString, value)
		_node.Condition = &value
	}
	if value, ok := adc.mutation.CreatedAt(); ok {
		_spec.SetField(agentdependency.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := adc.mutation.AgentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agentdependency.AgentTable,
			Columns: []string{agentdependency.AgentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agent.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.agent_dependencies = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// AgentDependencyCreateBulk is the builder for creating many AgentDependency entities in bulk.
type AgentDependencyCreateBulk struct {
	config
	err      error
	builders []*AgentDependencyCreate
}

// Save creates the AgentDependency entities in the database.
func (adcb *AgentDependencyCreateBulk) Save(ctx context.Context) ([]*AgentDependency, error) {
	if adcb.err != nil {
		return nil, adcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(adcb.builders))
	nodes := make([]*AgentDependency, len(adcb.builders))
	mutators := make([]Mutator, len(adcb.builders))
	for i := range adcb.builders {
		func(i int, root context.Context) {
			builder := adcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AgentDependencyMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, adcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, adcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, adcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (adcb *AgentDependencyCreateBulk) SaveX(ctx context.Context) []*AgentDependency {
	v, err := adcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (adcb *AgentDependencyCreateBulk) Exec(ctx context.Context) error {
	_, err := adcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (adcb *AgentDependencyCreateBulk) ExecX(ctx context.Context) {
	if err := adcb.Exec(ctx); err != nil {
		panic(err)
	}
}
