// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/denkhaus/agentforge/internal/database/ent/componentdependency"
	"github.com/denkhaus/agentforge/internal/database/ent/predicate"
)

// ComponentDependencyDelete is the builder for deleting a ComponentDependency entity.
type ComponentDependencyDelete struct {
	config
	hooks    []Hook
	mutation *ComponentDependencyMutation
}

// Where appends a list predicates to the ComponentDependencyDelete builder.
func (cdd *ComponentDependencyDelete) Where(ps ...predicate.ComponentDependency) *ComponentDependencyDelete {
	cdd.mutation.Where(ps...)
	return cdd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (cdd *ComponentDependencyDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, cdd.sqlExec, cdd.mutation, cdd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (cdd *ComponentDependencyDelete) ExecX(ctx context.Context) int {
	n, err := cdd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (cdd *ComponentDependencyDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(componentdependency.Table, sqlgraph.NewFieldSpec(componentdependency.FieldID, field.TypeString))
	if ps := cdd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, cdd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	cdd.mutation.done = true
	return affected, err
}

// ComponentDependencyDeleteOne is the builder for deleting a single ComponentDependency entity.
type ComponentDependencyDeleteOne struct {
	cdd *ComponentDependencyDelete
}

// Where appends a list predicates to the ComponentDependencyDelete builder.
func (cddo *ComponentDependencyDeleteOne) Where(ps ...predicate.ComponentDependency) *ComponentDependencyDeleteOne {
	cddo.cdd.mutation.Where(ps...)
	return cddo
}

// Exec executes the deletion query.
func (cddo *ComponentDependencyDeleteOne) Exec(ctx context.Context) error {
	n, err := cddo.cdd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{componentdependency.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (cddo *ComponentDependencyDeleteOne) ExecX(ctx context.Context) {
	if err := cddo.Exec(ctx); err != nil {
		panic(err)
	}
}
