// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/denkhaus/agentforge/internal/database/ent/localconfig"
)

// LocalConfig is the model entity for the LocalConfig schema.
type LocalConfig struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// Key holds the value of the "key" field.
	Key string `json:"key,omitempty"`
	// Value holds the value of the "value" field.
	Value string `json:"value,omitempty"`
	// Type holds the value of the "type" field.
	Type localconfig.Type `json:"type,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*LocalConfig) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case localconfig.FieldID, localconfig.FieldKey, localconfig.FieldValue, localconfig.FieldType:
			values[i] = new(sql.NullString)
		case localconfig.FieldCreatedAt, localconfig.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the LocalConfig fields.
func (lc *LocalConfig) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case localconfig.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				lc.ID = value.String
			}
		case localconfig.FieldKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field key", values[i])
			} else if value.Valid {
				lc.Key = value.String
			}
		case localconfig.FieldValue:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field value", values[i])
			} else if value.Valid {
				lc.Value = value.String
			}
		case localconfig.FieldType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value.Valid {
				lc.Type = localconfig.Type(value.String)
			}
		case localconfig.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				lc.CreatedAt = value.Time
			}
		case localconfig.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				lc.UpdatedAt = value.Time
			}
		default:
			lc.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// GetValue returns the ent.Value that was dynamically selected and assigned to the LocalConfig.
// This includes values selected through modifiers, order, etc.
func (lc *LocalConfig) GetValue(name string) (ent.Value, error) {
	return lc.selectValues.Get(name)
}

// Update returns a builder for updating this LocalConfig.
// Note that you need to call LocalConfig.Unwrap() before calling this method if this LocalConfig
// was returned from a transaction, and the transaction was committed or rolled back.
func (lc *LocalConfig) Update() *LocalConfigUpdateOne {
	return NewLocalConfigClient(lc.config).UpdateOne(lc)
}

// Unwrap unwraps the LocalConfig entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (lc *LocalConfig) Unwrap() *LocalConfig {
	_tx, ok := lc.config.driver.(*txDriver)
	if !ok {
		panic("ent: LocalConfig is not a transactional entity")
	}
	lc.config.driver = _tx.drv
	return lc
}

// String implements the fmt.Stringer.
func (lc *LocalConfig) String() string {
	var builder strings.Builder
	builder.WriteString("LocalConfig(")
	builder.WriteString(fmt.Sprintf("id=%v, ", lc.ID))
	builder.WriteString("key=")
	builder.WriteString(lc.Key)
	builder.WriteString(", ")
	builder.WriteString("value=")
	builder.WriteString(lc.Value)
	builder.WriteString(", ")
	builder.WriteString("type=")
	builder.WriteString(fmt.Sprintf("%v", lc.Type))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(lc.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(lc.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// LocalConfigs is a parsable slice of LocalConfig.
type LocalConfigs []*LocalConfig
