// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/denkhaus/agentforge/internal/database/ent/localconfig"
	"github.com/denkhaus/agentforge/internal/database/ent/predicate"
)

// LocalConfigQuery is the builder for querying LocalConfig entities.
type LocalConfigQuery struct {
	config
	ctx        *QueryContext
	order      []localconfig.OrderOption
	inters     []Interceptor
	predicates []predicate.LocalConfig
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the LocalConfigQuery builder.
func (lcq *LocalConfigQuery) Where(ps ...predicate.LocalConfig) *LocalConfigQuery {
	lcq.predicates = append(lcq.predicates, ps...)
	return lcq
}

// Limit the number of records to be returned by this query.
func (lcq *LocalConfigQuery) Limit(limit int) *LocalConfigQuery {
	lcq.ctx.Limit = &limit
	return lcq
}

// Offset to start from.
func (lcq *LocalConfigQuery) Offset(offset int) *LocalConfigQuery {
	lcq.ctx.Offset = &offset
	return lcq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (lcq *LocalConfigQuery) Unique(unique bool) *LocalConfigQuery {
	lcq.ctx.Unique = &unique
	return lcq
}

// Order specifies how the records should be ordered.
func (lcq *LocalConfigQuery) Order(o ...localconfig.OrderOption) *LocalConfigQuery {
	lcq.order = append(lcq.order, o...)
	return lcq
}

// First returns the first LocalConfig entity from the query.
// Returns a *NotFoundError when no LocalConfig was found.
func (lcq *LocalConfigQuery) First(ctx context.Context) (*LocalConfig, error) {
	nodes, err := lcq.Limit(1).All(setContextOp(ctx, lcq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{localconfig.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (lcq *LocalConfigQuery) FirstX(ctx context.Context) *LocalConfig {
	node, err := lcq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first LocalConfig ID from the query.
// Returns a *NotFoundError when no LocalConfig ID was found.
func (lcq *LocalConfigQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = lcq.Limit(1).IDs(setContextOp(ctx, lcq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{localconfig.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (lcq *LocalConfigQuery) FirstIDX(ctx context.Context) string {
	id, err := lcq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single LocalConfig entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one LocalConfig entity is found.
// Returns a *NotFoundError when no LocalConfig entities are found.
func (lcq *LocalConfigQuery) Only(ctx context.Context) (*LocalConfig, error) {
	nodes, err := lcq.Limit(2).All(setContextOp(ctx, lcq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{localconfig.Label}
	default:
		return nil, &NotSingularError{localconfig.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (lcq *LocalConfigQuery) OnlyX(ctx context.Context) *LocalConfig {
	node, err := lcq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only LocalConfig ID in the query.
// Returns a *NotSingularError when more than one LocalConfig ID is found.
// Returns a *NotFoundError when no entities are found.
func (lcq *LocalConfigQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = lcq.Limit(2).IDs(setContextOp(ctx, lcq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{localconfig.Label}
	default:
		err = &NotSingularError{localconfig.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (lcq *LocalConfigQuery) OnlyIDX(ctx context.Context) string {
	id, err := lcq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of LocalConfigs.
func (lcq *LocalConfigQuery) All(ctx context.Context) ([]*LocalConfig, error) {
	ctx = setContextOp(ctx, lcq.ctx, ent.OpQueryAll)
	if err := lcq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*LocalConfig, *LocalConfigQuery]()
	return withInterceptors[[]*LocalConfig](ctx, lcq, qr, lcq.inters)
}

// AllX is like All, but panics if an error occurs.
func (lcq *LocalConfigQuery) AllX(ctx context.Context) []*LocalConfig {
	nodes, err := lcq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of LocalConfig IDs.
func (lcq *LocalConfigQuery) IDs(ctx context.Context) (ids []string, err error) {
	if lcq.ctx.Unique == nil && lcq.path != nil {
		lcq.Unique(true)
	}
	ctx = setContextOp(ctx, lcq.ctx, ent.OpQueryIDs)
	if err = lcq.Select(localconfig.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (lcq *LocalConfigQuery) IDsX(ctx context.Context) []string {
	ids, err := lcq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (lcq *LocalConfigQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, lcq.ctx, ent.OpQueryCount)
	if err := lcq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, lcq, querierCount[*LocalConfigQuery](), lcq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (lcq *LocalConfigQuery) CountX(ctx context.Context) int {
	count, err := lcq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (lcq *LocalConfigQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, lcq.ctx, ent.OpQueryExist)
	switch _, err := lcq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (lcq *LocalConfigQuery) ExistX(ctx context.Context) bool {
	exist, err := lcq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the LocalConfigQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (lcq *LocalConfigQuery) Clone() *LocalConfigQuery {
	if lcq == nil {
		return nil
	}
	return &LocalConfigQuery{
		config:     lcq.config,
		ctx:        lcq.ctx.Clone(),
		order:      append([]localconfig.OrderOption{}, lcq.order...),
		inters:     append([]Interceptor{}, lcq.inters...),
		predicates: append([]predicate.LocalConfig{}, lcq.predicates...),
		// clone intermediate query.
		sql:  lcq.sql.Clone(),
		path: lcq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Key string `json:"key,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.LocalConfig.Query().
//		GroupBy(localconfig.FieldKey).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (lcq *LocalConfigQuery) GroupBy(field string, fields ...string) *LocalConfigGroupBy {
	lcq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &LocalConfigGroupBy{build: lcq}
	grbuild.flds = &lcq.ctx.Fields
	grbuild.label = localconfig.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Key string `json:"key,omitempty"`
//	}
//
//	client.LocalConfig.Query().
//		Select(localconfig.FieldKey).
//		Scan(ctx, &v)
func (lcq *LocalConfigQuery) Select(fields ...string) *LocalConfigSelect {
	lcq.ctx.Fields = append(lcq.ctx.Fields, fields...)
	sbuild := &LocalConfigSelect{LocalConfigQuery: lcq}
	sbuild.label = localconfig.Label
	sbuild.flds, sbuild.scan = &lcq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a LocalConfigSelect configured with the given aggregations.
func (lcq *LocalConfigQuery) Aggregate(fns ...AggregateFunc) *LocalConfigSelect {
	return lcq.Select().Aggregate(fns...)
}

func (lcq *LocalConfigQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range lcq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, lcq); err != nil {
				return err
			}
		}
	}
	for _, f := range lcq.ctx.Fields {
		if !localconfig.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if lcq.path != nil {
		prev, err := lcq.path(ctx)
		if err != nil {
			return err
		}
		lcq.sql = prev
	}
	return nil
}

func (lcq *LocalConfigQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*LocalConfig, error) {
	var (
		nodes = []*LocalConfig{}
		_spec = lcq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*LocalConfig).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &LocalConfig{config: lcq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, lcq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (lcq *LocalConfigQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := lcq.querySpec()
	_spec.Node.Columns = lcq.ctx.Fields
	if len(lcq.ctx.Fields) > 0 {
		_spec.Unique = lcq.ctx.Unique != nil && *lcq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, lcq.driver, _spec)
}

func (lcq *LocalConfigQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(localconfig.Table, localconfig.Columns, sqlgraph.NewFieldSpec(localconfig.FieldID, field.TypeString))
	_spec.From = lcq.sql
	if unique := lcq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if lcq.path != nil {
		_spec.Unique = true
	}
	if fields := lcq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, localconfig.FieldID)
		for i := range fields {
			if fields[i] != localconfig.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := lcq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := lcq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := lcq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := lcq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (lcq *LocalConfigQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(lcq.driver.Dialect())
	t1 := builder.Table(localconfig.Table)
	columns := lcq.ctx.Fields
	if len(columns) == 0 {
		columns = localconfig.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if lcq.sql != nil {
		selector = lcq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if lcq.ctx.Unique != nil && *lcq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range lcq.predicates {
		p(selector)
	}
	for _, p := range lcq.order {
		p(selector)
	}
	if offset := lcq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := lcq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// LocalConfigGroupBy is the group-by builder for LocalConfig entities.
type LocalConfigGroupBy struct {
	selector
	build *LocalConfigQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (lcgb *LocalConfigGroupBy) Aggregate(fns ...AggregateFunc) *LocalConfigGroupBy {
	lcgb.fns = append(lcgb.fns, fns...)
	return lcgb
}

// Scan applies the selector query and scans the result into the given value.
func (lcgb *LocalConfigGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, lcgb.build.ctx, ent.OpQueryGroupBy)
	if err := lcgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*LocalConfigQuery, *LocalConfigGroupBy](ctx, lcgb.build, lcgb, lcgb.build.inters, v)
}

func (lcgb *LocalConfigGroupBy) sqlScan(ctx context.Context, root *LocalConfigQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(lcgb.fns))
	for _, fn := range lcgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*lcgb.flds)+len(lcgb.fns))
		for _, f := range *lcgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*lcgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := lcgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// LocalConfigSelect is the builder for selecting fields of LocalConfig entities.
type LocalConfigSelect struct {
	*LocalConfigQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (lcs *LocalConfigSelect) Aggregate(fns ...AggregateFunc) *LocalConfigSelect {
	lcs.fns = append(lcs.fns, fns...)
	return lcs
}

// Scan applies the selector query and scans the result into the given value.
func (lcs *LocalConfigSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, lcs.ctx, ent.OpQuerySelect)
	if err := lcs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*LocalConfigQuery, *LocalConfigSelect](ctx, lcs.LocalConfigQuery, lcs, lcs.inters, v)
}

func (lcs *LocalConfigSelect) sqlScan(ctx context.Context, root *LocalConfigQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(lcs.fns))
	for _, fn := range lcs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*lcs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := lcs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
