// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/denkhaus/agentforge/internal/database/ent/predicate"
	"github.com/denkhaus/agentforge/internal/database/ent/syncoperation"
)

// SyncOperationQuery is the builder for querying SyncOperation entities.
type SyncOperationQuery struct {
	config
	ctx        *QueryContext
	order      []syncoperation.OrderOption
	inters     []Interceptor
	predicates []predicate.SyncOperation
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the SyncOperationQuery builder.
func (soq *SyncOperationQuery) Where(ps ...predicate.SyncOperation) *SyncOperationQuery {
	soq.predicates = append(soq.predicates, ps...)
	return soq
}

// Limit the number of records to be returned by this query.
func (soq *SyncOperationQuery) Limit(limit int) *SyncOperationQuery {
	soq.ctx.Limit = &limit
	return soq
}

// Offset to start from.
func (soq *SyncOperationQuery) Offset(offset int) *SyncOperationQuery {
	soq.ctx.Offset = &offset
	return soq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (soq *SyncOperationQuery) Unique(unique bool) *SyncOperationQuery {
	soq.ctx.Unique = &unique
	return soq
}

// Order specifies how the records should be ordered.
func (soq *SyncOperationQuery) Order(o ...syncoperation.OrderOption) *SyncOperationQuery {
	soq.order = append(soq.order, o...)
	return soq
}

// First returns the first SyncOperation entity from the query.
// Returns a *NotFoundError when no SyncOperation was found.
func (soq *SyncOperationQuery) First(ctx context.Context) (*SyncOperation, error) {
	nodes, err := soq.Limit(1).All(setContextOp(ctx, soq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{syncoperation.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (soq *SyncOperationQuery) FirstX(ctx context.Context) *SyncOperation {
	node, err := soq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first SyncOperation ID from the query.
// Returns a *NotFoundError when no SyncOperation ID was found.
func (soq *SyncOperationQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = soq.Limit(1).IDs(setContextOp(ctx, soq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{syncoperation.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (soq *SyncOperationQuery) FirstIDX(ctx context.Context) string {
	id, err := soq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single SyncOperation entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one SyncOperation entity is found.
// Returns a *NotFoundError when no SyncOperation entities are found.
func (soq *SyncOperationQuery) Only(ctx context.Context) (*SyncOperation, error) {
	nodes, err := soq.Limit(2).All(setContextOp(ctx, soq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{syncoperation.Label}
	default:
		return nil, &NotSingularError{syncoperation.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (soq *SyncOperationQuery) OnlyX(ctx context.Context) *SyncOperation {
	node, err := soq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only SyncOperation ID in the query.
// Returns a *NotSingularError when more than one SyncOperation ID is found.
// Returns a *NotFoundError when no entities are found.
func (soq *SyncOperationQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = soq.Limit(2).IDs(setContextOp(ctx, soq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{syncoperation.Label}
	default:
		err = &NotSingularError{syncoperation.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (soq *SyncOperationQuery) OnlyIDX(ctx context.Context) string {
	id, err := soq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of SyncOperations.
func (soq *SyncOperationQuery) All(ctx context.Context) ([]*SyncOperation, error) {
	ctx = setContextOp(ctx, soq.ctx, ent.OpQueryAll)
	if err := soq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*SyncOperation, *SyncOperationQuery]()
	return withInterceptors[[]*SyncOperation](ctx, soq, qr, soq.inters)
}

// AllX is like All, but panics if an error occurs.
func (soq *SyncOperationQuery) AllX(ctx context.Context) []*SyncOperation {
	nodes, err := soq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of SyncOperation IDs.
func (soq *SyncOperationQuery) IDs(ctx context.Context) (ids []string, err error) {
	if soq.ctx.Unique == nil && soq.path != nil {
		soq.Unique(true)
	}
	ctx = setContextOp(ctx, soq.ctx, ent.OpQueryIDs)
	if err = soq.Select(syncoperation.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (soq *SyncOperationQuery) IDsX(ctx context.Context) []string {
	ids, err := soq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (soq *SyncOperationQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, soq.ctx, ent.OpQueryCount)
	if err := soq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, soq, querierCount[*SyncOperationQuery](), soq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (soq *SyncOperationQuery) CountX(ctx context.Context) int {
	count, err := soq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (soq *SyncOperationQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, soq.ctx, ent.OpQueryExist)
	switch _, err := soq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (soq *SyncOperationQuery) ExistX(ctx context.Context) bool {
	exist, err := soq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the SyncOperationQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (soq *SyncOperationQuery) Clone() *SyncOperationQuery {
	if soq == nil {
		return nil
	}
	return &SyncOperationQuery{
		config:     soq.config,
		ctx:        soq.ctx.Clone(),
		order:      append([]syncoperation.OrderOption{}, soq.order...),
		inters:     append([]Interceptor{}, soq.inters...),
		predicates: append([]predicate.SyncOperation{}, soq.predicates...),
		// clone intermediate query.
		sql:  soq.sql.Clone(),
		path: soq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Type syncoperation.Type `json:"type,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.SyncOperation.Query().
//		GroupBy(syncoperation.FieldType).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (soq *SyncOperationQuery) GroupBy(field string, fields ...string) *SyncOperationGroupBy {
	soq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &SyncOperationGroupBy{build: soq}
	grbuild.flds = &soq.ctx.Fields
	grbuild.label = syncoperation.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Type syncoperation.Type `json:"type,omitempty"`
//	}
//
//	client.SyncOperation.Query().
//		Select(syncoperation.FieldType).
//		Scan(ctx, &v)
func (soq *SyncOperationQuery) Select(fields ...string) *SyncOperationSelect {
	soq.ctx.Fields = append(soq.ctx.Fields, fields...)
	sbuild := &SyncOperationSelect{SyncOperationQuery: soq}
	sbuild.label = syncoperation.Label
	sbuild.flds, sbuild.scan = &soq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a SyncOperationSelect configured with the given aggregations.
func (soq *SyncOperationQuery) Aggregate(fns ...AggregateFunc) *SyncOperationSelect {
	return soq.Select().Aggregate(fns...)
}

func (soq *SyncOperationQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range soq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, soq); err != nil {
				return err
			}
		}
	}
	for _, f := range soq.ctx.Fields {
		if !syncoperation.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if soq.path != nil {
		prev, err := soq.path(ctx)
		if err != nil {
			return err
		}
		soq.sql = prev
	}
	return nil
}

func (soq *SyncOperationQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*SyncOperation, error) {
	var (
		nodes = []*SyncOperation{}
		_spec = soq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*SyncOperation).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &SyncOperation{config: soq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, soq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (soq *SyncOperationQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := soq.querySpec()
	_spec.Node.Columns = soq.ctx.Fields
	if len(soq.ctx.Fields) > 0 {
		_spec.Unique = soq.ctx.Unique != nil && *soq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, soq.driver, _spec)
}

func (soq *SyncOperationQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(syncoperation.Table, syncoperation.Columns, sqlgraph.NewFieldSpec(syncoperation.FieldID, field.TypeString))
	_spec.From = soq.sql
	if unique := soq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if soq.path != nil {
		_spec.Unique = true
	}
	if fields := soq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, syncoperation.FieldID)
		for i := range fields {
			if fields[i] != syncoperation.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := soq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := soq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := soq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := soq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (soq *SyncOperationQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(soq.driver.Dialect())
	t1 := builder.Table(syncoperation.Table)
	columns := soq.ctx.Fields
	if len(columns) == 0 {
		columns = syncoperation.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if soq.sql != nil {
		selector = soq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if soq.ctx.Unique != nil && *soq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range soq.predicates {
		p(selector)
	}
	for _, p := range soq.order {
		p(selector)
	}
	if offset := soq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := soq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// SyncOperationGroupBy is the group-by builder for SyncOperation entities.
type SyncOperationGroupBy struct {
	selector
	build *SyncOperationQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (sogb *SyncOperationGroupBy) Aggregate(fns ...AggregateFunc) *SyncOperationGroupBy {
	sogb.fns = append(sogb.fns, fns...)
	return sogb
}

// Scan applies the selector query and scans the result into the given value.
func (sogb *SyncOperationGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, sogb.build.ctx, ent.OpQueryGroupBy)
	if err := sogb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SyncOperationQuery, *SyncOperationGroupBy](ctx, sogb.build, sogb, sogb.build.inters, v)
}

func (sogb *SyncOperationGroupBy) sqlScan(ctx context.Context, root *SyncOperationQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(sogb.fns))
	for _, fn := range sogb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*sogb.flds)+len(sogb.fns))
		for _, f := range *sogb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*sogb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := sogb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// SyncOperationSelect is the builder for selecting fields of SyncOperation entities.
type SyncOperationSelect struct {
	*SyncOperationQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (sos *SyncOperationSelect) Aggregate(fns ...AggregateFunc) *SyncOperationSelect {
	sos.fns = append(sos.fns, fns...)
	return sos
}

// Scan applies the selector query and scans the result into the given value.
func (sos *SyncOperationSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, sos.ctx, ent.OpQuerySelect)
	if err := sos.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SyncOperationQuery, *SyncOperationSelect](ctx, sos.SyncOperationQuery, sos, sos.inters, v)
}

func (sos *SyncOperationSelect) sqlScan(ctx context.Context, root *SyncOperationQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(sos.fns))
	for _, fn := range sos.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*sos.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := sos.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
