// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/denkhaus/agentforge/internal/database/ent/predicate"
	"github.com/denkhaus/agentforge/internal/database/ent/syncoperation"
)

// SyncOperationDelete is the builder for deleting a SyncOperation entity.
type SyncOperationDelete struct {
	config
	hooks    []Hook
	mutation *SyncOperationMutation
}

// Where appends a list predicates to the SyncOperationDelete builder.
func (sod *SyncOperationDelete) Where(ps ...predicate.SyncOperation) *SyncOperationDelete {
	sod.mutation.Where(ps...)
	return sod
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (sod *SyncOperationDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, sod.sqlExec, sod.mutation, sod.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (sod *SyncOperationDelete) ExecX(ctx context.Context) int {
	n, err := sod.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (sod *SyncOperationDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(syncoperation.Table, sqlgraph.NewFieldSpec(syncoperation.FieldID, field.TypeString))
	if ps := sod.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, sod.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	sod.mutation.done = true
	return affected, err
}

// SyncOperationDeleteOne is the builder for deleting a single SyncOperation entity.
type SyncOperationDeleteOne struct {
	sod *SyncOperationDelete
}

// Where appends a list predicates to the SyncOperationDelete builder.
func (sodo *SyncOperationDeleteOne) Where(ps ...predicate.SyncOperation) *SyncOperationDeleteOne {
	sodo.sod.mutation.Where(ps...)
	return sodo
}

// Exec executes the deletion query.
func (sodo *SyncOperationDeleteOne) Exec(ctx context.Context) error {
	n, err := sodo.sod.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{syncoperation.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (sodo *SyncOperationDeleteOne) ExecX(ctx context.Context) {
	if err := sodo.Exec(ctx); err != nil {
		panic(err)
	}
}
