apiVersion: agentforge.dev/v1
kind: Prompt
metadata:
  name: final-test-prompt
  namespace: default
  version: 1.0.0
  description: AI prompt for Final Test Prompt

spec:
  prompt:
    type: TEMPLATE
    language: en
    template_file: template.txt
    variables_file: variables.json
